name: Build The Theme & Deploy
on:
  push:
    branches:
      - dev-deploy
  pull_request:
    branches:
      - dev-deploy
    types: [closed]
defauls:
  run:
    working-directory: themes/my-theme
jobs:
  run-github-action:
    runs-on: ubuntu-latest